### ISSUE TITLE
Inputs sometimes not updating

### ISSUE THREAD

**Issue by Planeshifter** [Planeshifter/qality.js#16] opened 2015-04-29 22:07 UTC
Input fields are not updated: Hitting "Submit" when changing the settings of a node will  cause the input to be lost and the instance properties won't be changed.

**Comment by Planeshifter** [comment] 2015-04-29 22:39
I think I have identified the reason: Both MultipleChoice and  Input create a settings div, containing elements with the same ID names. This messes things up since our IDs are not unique anymore.

**Comment by Planeshifter** [comment] 2015-04-29 22:54
Or maybe not, problem persists for me.

**Comment by Phalanstere** [comment] 2015-04-30 08:27
test  1

An Input - a Multiple Choice - switch - successful 

test 2
IP - MP - IP - suceessfull

test 3

**Comment by Phalanstere** [comment] 2015-04-30 08:45
Ok, I can confirm - there is a problem. It seems to happen if you click the setting window again beore the fadeOut is executed

**Comment by Phalanstere** [comment] 2015-04-30 08:50
seem to be fixed now. The reason why it happened? There were two setting windows existent, therefore the assignment of transition_in and transition_out did not work. 
Please check it again. If it works for you we can close it.

**Closed as completed** 2015-05-02 07:44 UTC
Labels: bug, help wanted
